name: "spine_icarus_full_chain"
backend: "python"

max_batch_size: 0

input [
  {
    name: "COORDINATES"
    data_type: TYPE_INT32
    dims: [ -1, 4 ]
  },
  {
    name: "FEATURES"
    data_type: TYPE_FP32
    dims: [ -1, 8 ]
  },
  {
    name: "SOURCES"
    data_type: TYPE_INT32
    dims: [ -1, 2 ]
  },
  {
    name: "COUNTS"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "META"
    data_type: TYPE_FP32
    dims: [ -1, 12 ]
  },
  {
    name: "RUN_INFO"
    data_type: TYPE_INT64
    dims: [ -1, 3 ]
  },
  {
    name: "FLASH_DATA"
    data_type: TYPE_FP32
    dims: [ -1, 16 ]
    optional: true
  },
  {
    name: "FLASH_PE"
    data_type: TYPE_FP32
    dims: [ -1, 180 ]
    optional: true
  },
  {
    name: "FLASH_COUNTS"
    data_type: TYPE_INT32
    dims: [ -1 ]
    optional: true
  }
]

output [
  {
    name: "EVENT_ID"
    data_type: TYPE_INT64
    dims: [ -1, 3 ]
  },
  {
    name: "GHOST_PRED"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "GHOST_COUNTS"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "SEGMENTATION"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "SEGMENTATION_COUNTS"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "ORIG_INDEX"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "POINTS"
    data_type: TYPE_FP32
    dims: [ -1, 3 ]
  },
  {
    name: "DEPOSITIONS"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "DEGHOSTED_SOURCES"
    data_type: TYPE_INT32
    dims: [ -1, 2 ]
  },
  {
    name: "PARTICLES"
    data_type: TYPE_FP32
    dims: [ -1, 41 ]
  },
  {
    name: "PARTICLE_COUNTS"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "PARTICLE_VOXELS"
    data_type: TYPE_INT64
    dims: [ -1, 3 ]
  },
  {
    name: "PARTICLE_VOXEL_COUNTS"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "INTERACTIONS"
    data_type: TYPE_FP32
    dims: [ -1, 29 ]
  },
  {
    name: "INTERACTION_COUNTS"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "INTERACTION_FLASHES"
    data_type: TYPE_FP32
    dims: [ -1, 6 ]
  },
  {
    name: "INTERACTION_FLASH_COUNTS"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "FLASH_MATCH_RAN"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
]

version_policy {
  specific {
    versions: [ 1 ]
  }
}

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
