# ICARUS backward SCE detector variation modifier
# Revision date: August 13, 2026

__meta__:
  kind: mod
  name: "sce_backward"
  version: "260813"
  date: "2026-08-13"
  description: "Backward SCE detector variation"
  applies_to: [mc]
  compatible_with:
    model: ">=250303"
  conflicts_with: [sce_forward]

override:
  # Apply the displacement before charge calibrations.
  model.modules.calibration.field:
    priority: 10
    map_file: $ICARUS_DATA_DIR/v10_06_06/icarus_data/SCEoffsets/SCEoffsets_ICARUS_E500_voxelTH3.root
    map_prefix: TrueBkwd_Displacement
