# ICARUS full chain configuration
# Revision date: January 15, 2025

__meta__:
  kind: bundle
  version: "250115"
  date: "2025-01-15"
  description: "ICARUS full chain configuration"

include:
  - base/base_240719.yaml
  - io/io_240812.yaml
  - model/model_250115.yaml
  - post/post_250115.yaml
