# ICARUS full chain configuration with collection-only model
# Revision date: February 12, 2026

__meta__:
  kind: bundle
  version: "260212"
  date: "2026-02-12"
  description: "ICARUS full chain configuration with collection-only model"

include:
  - base/base_240719.yaml
  - io/io_240812.yaml
  - model/model_co_260212.yaml
  - post/post_250625.yaml
