# ICARUS truth saving configuration
# Revision date: August 12, 2024

__meta__:
  kind: bundle
  version: "240812"
  date: "2024-08-12"
  description: "ICARUS truth saving configuration"

include:
  - base/base_240719.yaml
  - io/io_240812.yaml

# Overrides
override:
  # Only build truth objects
  build.mode: truth

  # Force CPU execution for truth-only parsing
  base.world_size: 0

  # Temporary workaround until SPINE produces sources labels without reco
  # No reconstructed information or wire-TPC-only source products to write
  io.writer.keys-:
    [
      points,
      depositions,
      reco_particles,
      reco_interactions,
      sources,
      sources_label,
    ]
